In [1]:
import numpy as np
import itertools

In [7]:
X = np.zeros(402)
X[-1] = 1

In [15]:
X[:48].shape
X[-48:].shape

(48,)

In [14]:
X[-48:]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [22]:
num_moments = 16
num_nodes = 27

for i_moment, i_node in enumerate(range(num_moments), range(num_nodes)):
    print(i_moment, i_node)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
11 11
12 12
13 13
14 14
15 15


In [7]:
X = np.linspace(1, 10, 10)
print(X)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [2]:
num_moments = 2
num_nodes = 4

flux = np.zeros(num_moments)

for m, n in itertools.product(range(num_moments), range(num_nodes)):
    print(m,", ",n,", ","m+n+1",m+n+1)
    flux[m] += m+n+1

0 ,  0 ,  m+n+1 1
0 ,  1 ,  m+n+1 2
0 ,  2 ,  m+n+1 3
0 ,  3 ,  m+n+1 4
1 ,  0 ,  m+n+1 2
1 ,  1 ,  m+n+1 3
1 ,  2 ,  m+n+1 4
1 ,  3 ,  m+n+1 5


In [16]:
flux

array([10., 14.])